[linters]
enable-all = true
disable = [
  "deadcode",         # deprecated
  "exhaustivestruct", # deprecated
  "golint",           # deprecated
  "gomnd",            # deprecated
  "maligned",         # deprecated
  "nosnakecase",      # deprecated
  "scopelint",        # deprecated
  "structcheck",      # deprecated
  "varcheck",         # deprecated
]
